### ISSUE TITLE
docs: runc doesn't need to be the default runtime

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/osbuilder#23]
The `README` says that one of the requirements is that, "`runc` is configured as default runtime" however, `Makefile` calls  `--runtime runc` so it doesn't matter what the default runtime is.

**Comment by grahamwhaley** [comment]
I have a feeling the issue is with the `docker build` step, not the `docker run` step, where having CC as the default runtime shows up a 9pfs unlink style problem when building the initial image. And iirc, you cannot state a runtime to use for `docker build`. That is iirc - so, asking @jcvenegas for confirmation :-)

**Comment by jodh-intel** [comment]
Ah - that would make sense. But we should document this in the README as it's currently unclear "why".

**Comment by jcvenegas** [comment]
@jodh-intel @grahamwhaley  yes, is because of docker build, sadly it does not support to change the runtime in that command.

**Comment by jodh-intel** [comment]
Limitations is documented in #8. Closing this.
